---
driver_plugin: docker
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu
  driver_config:
    image: ubuntu:12.04
  run_list:
    - tmux

suites:
- name: default
  run_list:
    - tmux
  attributes: {}

busser:
  sudo: true
